# column titles
columns = [
    "Group Name",  # tup(0)
    "Team Name",  # tup(1)
    "Games",  # tup(2)- start of JSON object
    "Wins",
    "Win Percentage",
    "Play Duration",
    "Core- Shots",  # within core object
    "Core- Shots Against",
    "Core- Goals",
    "Core- Goals Against",
    "Core- Saves",
    "Core- Assists",
    "Core- Score",
    "Core- MVP",
    "Core- Shooting Percentage",
    "Boost- BPM",  # within boost object
    "Boost- BCPM",
    "Boost- Avg. Amount",
    "Boost- Amount Collected",
    "Boost- Amount Stolen",
    "Boost- Amount Collected (Big)",
    "Boost- Amount Stolen (Big)",
    "Boost- Amount Collected (Small)",
    "Boost- Amount Stolen (Small)",
    "Boost- Count Collected (Big)",
    "Boost- Count Stolen (Big)",
    "Boost- Count Collected (Small)",
    "Boost- Count Stolen (Small)",
    "Boost- Time w/ Zero Boost",
    "Boost- Percent w/ Zero Boost",
    "Boost- Time w/ Full Boost",
    "Boost- Percent w/ Full Boost",
    "Boost- Amount of Overfill",
    "Boost- Amount of Overfill Stolen",
    "Boost- Amount Used While Supersonic",
    "Boost- Time of Boost (0-25)",
    "Boost- Time of Boost (25-50)",
    "Boost- Time of Boost (50-75)",
    "Boost- Time of Boost (75-100)",
    "Boost- Percent of Boost (0-25)",
    "Boost- Percent of Boost (25-50)",
    "Boost- Percent of Boost (50-75)",
    "Boost- Percent of Boost (75-100)",
    "Movement- Avg. Speed",  # within movement object
    "Movement- Total Distance",
    "Movement- Time in Supersonic Speed",
    "Movement- Time in Boost Speed",
    "Movement- Time in Slow Speed",
    "Movement- Time on Ground",
    "Movement- Time in Air (Low)",
    "Movement- Time in Air (High)",
    "Movement- Time in Powerslide",
    "Movement- Powerslide Count",
    "Movement- Avg. Powerslide Duration",
    "Movement- Avg. Speed Percentage",
    "Movement- Percent in Slow Speed",
    "Movement- Percent in Boost Speed",
    "Movement- Percent in Supersonic Speed",
    "Movement- Percent on Ground",
    "Movement- Percent in Air (Low)",
    "Movement- Percent in Air (High)",
    "Positioning- Avg. Dist. to Ball",  # within positioning object
    "Positioning- Avg. Dist. to Ball (Possession)",
    "Positioning- Avg. Dist. to Ball (No Possession)",
    "Positioning- Time in Defensive Third",
    "Positioning- Time in Neutral Third",
    "Positioning- Time in Offensive Third",
    "Positioning- Time in Defensive Half",
    "Positioning- Time in Offensive Half",
    "Positioning- Time Behind Ball",
    "Positioning- Time in Front of Ball",
    "Positioning- Time Most Back",
    "Positioning- Time Most Forward",
    "Positioning- GA while the Last Defender",
    "Positioning- Time Closest to Ball",
    "Positioning- Time Farthest from Ball",
    "Positioning- Percent in Defensive Third",
    "Positioning- Percent in Offensive Third",
    "Positioning- Percent in Neutral Third",
    "Positioning- Percent in Defensive Half",
    "Positioning- Percent in Offensive Half",
    "Positioning- Percent Behind Ball",
    "Positioning- Percent in Front of Ball",
    "Demo- Inflicted",  # within demo object
    "Demo- Taken"
]
